name: reusable workflow
on:
  workflow_dispatch:
  input:
    node-version:
      description: 'Node version'
      default: 'lts/*'
      required: false
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: setup node
        uses: actions/setup-node
        with:
          node-version: 'lts/*'
      - name: run test
        shell: bash
        run: |
          node -v
          npm install
          npm test