name: reusable workflow
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        default: 'lts/*'
        required: false
        type: string
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: ${{inputs.node-version}}
      - name: run test
        shell: bash
        run: |
          node -v
          npm install
          npm test