name: npm test one job
on:
  workflow_dispatch:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout
      - name : setup node
        uses: actions/setup-node
        with:
          node-version: 'lts/*'
      - name: run test
        shell: bash
        run: |
          npm install
          npm test