name: Build

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Setup node
        uses: actions/setup-node
        with:
          node-version: 'lts/*'